### ISSUE TITLE
Thanks a lot , but can you tell how to use it ?

### ISSUE THREAD

**Issue by uokivan** [luccasr73/ionic-escpos-bluetooth-printer-sample#1]
have sample for home.html / home.ts ??

**Comment by luccasr73** [comment]
This repo is a sample, [see it](https://github.com/luccasr73/ionic-escpos-bluetooth-printer-sample/tree/master/ionic-escpos-bluetooth-printer-sample)

**Comment by uokivan** [comment]
Thank you so much
