### ISSUE TITLE
now it's posible print image?

### ISSUE THREAD

**Issue by alejandrojcc** [luccasr73/ionic-escpos-bluetooth-printer-sample#10]
Hi @luccasr73 now it's posible print images?

**Comment by luccasr73** [comment]
No, this is not possible, pull requests are appreciated

**Comment by alejandrojcc** [comment]
Hi @luccasr73 I already managed to print the qr, in a few days I will send you a pull request

**Comment by luccasr73** [comment]
> Hi @luccasr73 I already managed to print the qr, in a few days I will send you a pull request

Can explain how you made this?
