### ISSUE TITLE
How to migrate to ionic 4?

### ISSUE THREAD

**Issue by CristianGmz** [luccasr73/ionic-escpos-bluetooth-printer-sample#12]
I am getting this error, apparently there are parameters that do not work in ionic 4, how could I solve it?
![question](https://user-images.githubusercontent.com/38111597/62512057-a5d9af00-b7d3-11e9-923d-17d0829b06e5.jpg)

**Comment by uokivan** [comment]
Hi @CristianGmz ,
do you find any plugin for ionic 4 for pos printer ?

**Comment by luccasr73** [comment]
I planning to do this on the next weeks

**Comment by uokivan** [comment]
@luccasr73 
Thank you so so much, by the way, may be you can take a look about the "https://github.com/cirrushr/Cordova-Plugin-Bluetooth-Printer",
that plugin can print "Text" ,  "POS Commands" and  "Image" , although it said that can't print image, but I use it and confirm that, it can print image,

Thank you very much again

**Comment by lajith111** [comment]
@CristianGmz u find any solution?

Thanks

**Comment by lajith111** [comment]
> I planning to do this on the next weeks

Any update on ionic 5?  Thanks

**Comment by lajith111** [comment]
https://github.com/Ans0n-Ti0/EscPosEncoder/blob/master/src/esc-pos-encoder.js

This is updated to ionic 5..please check
