### ISSUE TITLE
Getting error  ReferenceError: Cannot access 'HomePageModule' before initialization

### ISSUE THREAD

**Issue by jayeshagwan1** [luccasr73/ionic-escpos-bluetooth-printer-sample#18]
I am using Ionic v5. I installed using **npm i esc-pos-encoder-ionic** and added import EscPosEncoder from "esc-pos-encoder-ionic"; on Home Page. I am getting error  **ReferenceError: Cannot access 'HomePageModule' before initialization**.

I have followed all the steps provided on https://www.npmjs.com/package/esc-pos-encoder-ionic .

Request @luccasr73  to look in to the issue.

I cloned this repo and follwed instructions. This repo works, but not if created in in Ionic 5

**Comment by luccasr73** [comment]
Sorry this not made to work with ionic 3, I planning to do samples with ionic 4 and 5 when I have free time

**Comment by jayeshagwan1** [comment]
Thanks for the update @luccasr73
