### ISSUE TITLE
can't print chinese word

### ISSUE THREAD

**Issue by uokivan** [luccasr73/ionic-escpos-bluetooth-printer-sample#2]
Thanks very much, I can print English and numbers,
but can't print Chinese word...., such as "謝謝",
how to fix it ?
Thanks a lot

**Comment by luccasr73** [comment]
Remove "noSpecialChars" function

**Comment by uokivan** [comment]
I will try for it, Thanks a lot

**Comment by luccasr73** [comment]
#6

**Comment by luccasr73** [comment]
#6

**Comment by luccasr73** [comment]
solved in #6

**Comment by luccasr73** [comment]
b40d6f48f3b1f75e7cddc3b0c731083ea9a557cf
