### ISSUE TITLE
Integration with Ionic4

### ISSUE THREAD

**Issue by jigarce** [luccasr73/ionic-escpos-bluetooth-printer-sample#4]
Hi,

Can you please update this code with ionic 4.

alert is not working with ionic4.

not able to add addInput in ionic4 using loop.

Please suggest  how do i convert below in ionic 4 alerts.
------------------------------------------------
` devices.forEach((device) => {
                            console.log('Devices: ', JSON.stringify(device));
                                                      

                            alert.addInput({
                                    name: 'printer',
                                    value: device.address,
                                    label: device.name,
                                    type: 'radio',
                                });
                        });
                        alert.present();`

**Comment by luccasr73** [comment]
I'm having a little free time but planning on doing it in the coming weeks

**Comment by alejandrojcc** [comment]
Hi @jigarce I load device in ngoninit and after show this:
`async mountAlertBt(data) {

    this.receipt = data;
    const alert = await this.alertCtrl.create({
      header: 'Select your printer',
      subHeader: 'Ingrese su nombre:',
      inputs: this.devicesBT,
      buttons: [
        {
          text: 'Cancel',
          role: 'cancel',
          handler: () => {
            console.log('Confirm Cancel');
          }
        },
        {
          text: 'Select printer',
          handler: (device) => {
            if (!device) {
              this.showToast('Select a printer!');
              return false;
            }
            console.log(device);
            this.print(device, this.receipt);
          },
        },
      ]
    });
    await alert.present();
  }`

**Comment by jigarce** [comment]
Thanks!

**Comment by CristianGmz** [comment]
> Hola @jigarce , cargo el dispositivo en ngoninit y después de mostrar esto: 
> `async mountAlertBt (data) {
> 
> ```
> this.receipt = data;
> const alert = await this.alertCtrl.create({
>   header: 'Select your printer',
>   subHeader: 'Ingrese su nombre:',
>   inputs: this.devicesBT,
>   buttons: [
>     {
>       text: 'Cancel',
>       role: 'cancel',
>       handler: () => {
>         console.log('Confirm Cancel');
>       }
>     },
>     {
>       text: 'Select printer',
>       handler: (device) => {
>         if (!device) {
>           this.showToast('Select a printer!');
>           return false;
>         }
>         console.log(device);
>         this.print(device, this.receipt);
>       },
>     },
>   ]
> });
> await alert.present();
> ```
> 
> } `

Do you have the complete code for ionic 4?
